### ISSUE TITLE
Exception on run example

### ISSUE THREAD

**Issue by claudiobadii** [digs-uwo/dcsim#6]
Exception in thread "main" java.lang.NumberFormatException: For input string: "0 "
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:441)
    at java.lang.Long.parseLong(Long.java:483)
    at edu.uwo.csd.dcsim.core.metrics.ApplicationMetrics.<init>(ApplicationMetrics.java:55)
    at edu.uwo.csd.dcsim.core.metrics.SimulationMetrics.<init>(SimulationMetrics.java:41)
    at edu.uwo.csd.dcsim.core.Simulation.<init>(Simulation.java:236)
    at edu.uwo.csd.dcsim.SimulationTask.<init>(SimulationTask.java:31)
    at edu.uwo.csd.dcsim.examples.ApplicationExample.<init>(ApplicationExample.java:48)
    at edu.uwo.csd.dcsim.examples.ApplicationExample.main(ApplicationExample.java:37)

The problem should be in row 614 on Simulation Class, with the property appSlaGraceTime

prop = getProperties().getProperty(name);

**Comment by mtighe** [comment]
Specifically which example are you running? Also, I would check your config/simulation.properties file, and check whether there is some strange whitespace character after appSlaGraceTime=0. Try adding a newline directly after the 0, or making sure there is nothing there after the 0. It sounds like that is the problem. Let me know if that clears it up.

**Comment by antomaka** [comment]
Thank you it worked for me!
